### ISSUE TITLE
Exception thrown for expressions with scientific notation (e.g. "1e2d")

### ISSUE THREAD

**Issue by lipchev** [miroiu/string-math#14]
Just a heads up:
An exception is thrown when attempting to execute the following command:
`"1e2d".Eval()`

> Unexpected token `e` at position 2. Expected [EOC]

The exception is thrown at

`   at StringMath.Parser.Parse()
   at StringMath.MathExprExtensions.Eval(String value)`

Cheers

**Comment by miroiu** [comment]
Hi, scientific notation is not supported. Feel free to reopen the issue if you need more information.
