### ISSUE TITLE
Expression compilation refering to PI global variable.

### ISSUE THREAD

**Issue by dnmnsmith** [miroiu/string-math#8]
Based on one of the examples:

            var try1 = "{a} + 2 + {PI}".ToMathExpr();
            var res1 = try1.Substitute("a", 5).Result;

This evaluates as expected, evidently PI exists as a global variable. Trying to compile this to a function doesn't go so well:

            Func<double, double> fn = "{a} + 2 + {PI}".ToMathExpr().Compile("a");
            double result = fn(5); // 7 + PI

This throws an exception at the Compile stage with "Variable 'PI' does not exist.".

Should this work, or am I missing something? Sorry, new to StringMath, trying to get to grips.

Building with 4.1.1.

Thanks!

   Duncan

**Comment by miroiu** [comment]
Hi, that's a bug. I'm gonna release a fix later today.

Thanks!

**Comment by dnmnsmith** [comment]
Thank you!
